name: Build site and deploy to Hetzner

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: "Build Site"
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Deploy via rsync to Hetzner
        uses: burnett01/rsync-deployments@v7.0.2
        with:
          switches: -avz --delete
          path: _site/
          remote_path: /var/www/gundelsby.com/
          remote_host: ${{ secrets.HETZNER_HOST }}
          remote_user: ${{ secrets.HETZNER_USER }}
          remote_key: ${{ secrets.HETZNER_KEY }}
