name: Build site and deploy to Bunny.net

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: "Build Site"
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to Bunny CDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.2
        with:
          source: "_site"
          destination: ""
          storageZoneName: "gundelsby-com-webpage"
          storagePassword: ${{ secrets.BUNNY_STORAGE_PASSWORD }}
          accessKey: ${{ secrets.BUNNY_API_KEY }}
          pullZoneId: ${{ secrets.BUNNY_PULL_ZONE_ID }}
          upload: "true"
          remove: "true"
          purgePullZone: "true"
