name: Build site and deploy to Hetzner

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: "Build Site"
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      
      - name: Upload site to Hetzner via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.HETZNER_KEY }}
          source: "_site/*"
          target: "/var/www/gundelsby.com"
