name: Build site and deploy to Hetzner

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: "Build Site"
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Upload to Bunny CDN Storage
        run: |
          find _site -type f | while read file; do
            echo "Uploading: $file"
            curl -s -T "$file" \
              -H "AccessKey: ${{ secrets.BUNNY_STORAGE_PASSWORD }}" \
              "https://storage.bunnycdn.com/gundelsby-com-webpage/${file#_site/}" \
              --fail || { echo "❌ Failed uploading $file" ; exit 1; }
          done

  
