name: Build site and deploy to Bunny.net

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true

      - name: "Build Site"
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Install bunny-launcher
        run: npm install -g bunny-launcher

      - name: Deploy to Bunny CDN Storage
        run: bunny-launcher deploy ./_site --storage-zone gundelsby-com-webpage
        env:
          BUNNY_STORAGE_PASSWORD: ${{ secrets.BUNNY_STORAGE_PASSWORD }}

  
